Tuan4/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tuan4.Models;

namespace Tuan4.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        MyDataDataContext db = new MyDataDataContext();
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, KhachHang kh)
        {
            var hoten = collection["hoten"];
            var tendangnhap = collection["tendangnhap"];
            var matkhau = collection["matkhau"];
            var MatKhauXacNhan = collection["MatKhauXacNhan"];
            var email = collection["email"];
            var diachi = collection["diachi"];
            var dienthoai = collection["dienthoai"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["ngaysinh"]);
            if (String.IsNullOrEmpty(MatKhauXacNhan))
            {
                ViewData["NhapMKXN"] = "Phải nhập mật khẩu xác nhận!";
            }
            else
            {
                if (!matkhau.Equals(MatKhauXacNhan))
                {
                    ViewData["MatKhauGiongNhau"] = "Mật khẩu và mật khẩu xác nhận phải giống nhau";
                }
                else
                {
                    kh.hoten = hoten;
                    kh.tendangnhap = tendangnhap;
                    kh.matkhau = matkhau;
                    kh.email = email;
                    kh.diachi = diachi;
                    kh.dienthoai = dienthoai;
                    kh.ngaysinh = DateTime.Parse(ngaysinh);
                    db.KhachHangs.InsertOnSubmit(kh);
                    db.SubmitChanges();
                    return RedirectToAction("DangNhap");
                }
            }
            return this.DangKy();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        public ActionResult DangNhap(FormCollection collection)
        {
            var tendangnhap = collection["tendangnhap"];
            var matkhau = collection["matkhau"];
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => tendangnhap == tendangnhap && n.matkhau == matkhau);
            if (kh != null)
            {
                ViewBag.ThongBao = "Chúc mừng bạn đăng nhập thành công";
                Session["TaiKhoan"] = kh;
            }
            else
            {
                ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

Tuan4/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tuan4.Models;
namespace Tuan4.Controllers
{
    public class SachController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        // GET: Sach
        public ActionResult ListSach()
        {
            var all_sach = from ss in data.Saches select ss;
            return View(all_sach);
        }
        public ActionResult Detail(int id)
        {
            var D_sach = data.Saches.Where(m => m.masach == id).First();
            return View(D_sach);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, Sach s)
        {
            var E_tensach = collection["tensach"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycapnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.tensach = E_tensach.ToString();
                s.hinh = E_hinh.ToString();
                s.giaban = E_giaban;
                s.ngaycapnhat = E_ngaycapnhat;
                s.soluongton = E_soluongton;
                data.Saches.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("ListSach");
            }
            return this.Create();
        }
        public ActionResult Edit(int id)
        {
            var E_sach = data.Saches.First(m => m.masach == id);
            return View(E_sach);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)


{
var E_sach = data.Saches.First(m => m.masach == id);
        var E_tensach = collection["tensach"];
        var E_hinh = collection["hinh"];
        var E_giaban = Convert.ToDecimal(collection["giaban"]);
        var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycatnhat"]);
        var E_soluongton = Convert.ToInt32(collection["soluongton"]);
        E_sach.masach = id;
if (string.IsNullOrEmpty(E_tensach))
{
ViewData["Error"] = "Don't empty!";
}
else
{
E_sach.tensach = E_tensach;
E_sach.hinh = E_hinh;
E_sach.giaban = E_giaban;
E_sach.ngaycapnhat = E_ngaycapnhat;
E_sach.soluongton = E_soluongton;
UpdateModel(E_sach);
    data.SubmitChanges();
return RedirectToAction("ListSach");
}
return this.Edit(id);
}
//-----------------------------------------
public ActionResult Delete(int id)
{
    var D_sach = data.Saches.First(m => m.masach == id);
    return View(D_sach);
}
[HttpPost]
public ActionResult Delete(int id, FormCollection collection)
{
    var D_sach = data.Saches.Where(m => m.masach == id).First();
    data.Saches.DeleteOnSubmit(D_sach);
    data.SubmitChanges();
    return RedirectToAction("ListSach");
    }
    public string ProcessUpload(HttpPostedFileBase file)
    {
        if (file == null)
        {
            return "";
        }
        file.SaveAs(Server.MapPath("~/Content/images/" + file.FileName));
        return "/Content/images/" + file.FileName;
    }
    }

}

Tuan4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Hutech Sách", "Index", "Home")</li>
                    <li>@Html.ActionLink("Thể loại", "Index", "Theloai")</li>
                    <li>@Html.ActionLink("Sách", "ListSach", "Sach")</li>
                    <li>@Html.ActionLink("Đăng Nhập", "DangNhap", "NguoiDung")</li>
                    <li>@Html.ActionLink("Đăng Ký", "DangKy", "NguoiDung")</li>
                    <li>@Html.Partial("~/Views/GioHang/GioHangPartial.cshtml")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("upload", required: false)

</body>
</html>